In [1]:
import pandas as pd

In [2]:
!mkdir -p data
![ -f data/Comorbid.xlsx ] || curl -L https://raw.githubusercontent.com/giovastabile/elaborazione_statistica/main/notebooks/data/Comorbid.xlsx -o data/Comorbid.xlsx

In [3]:
df = pd.read_excel('data/Comorbid.xlsx')

In [5]:
type(df)

pandas.core.frame.DataFrame

In [6]:
df.head()

,Age,Grade,Logistics,Temperature,Pneumonia,Hypertension,DiabetesMellitus
0,77,B,Immediate Surgical intervention(then Ward / IC...,37.4,No,No,No
1,64,A,Admit to Ward for Care,38.0,No,Yes,No
2,87,A,Admit to Ward for Care,38.5,No,No,No
3,70,A,Admit to Ward for Care,38.2,No,No,No
4,85,B,Admit to Ward for Care,38.1,No,Yes,No

In [7]:
df.tail()

,Age,Grade,Logistics,Temperature,Pneumonia,Hypertension,DiabetesMellitus
592,54,A,Admit to Ward for Care,39.9,No,No,No
593,40,B,Admit to Ward for Care,39.0,No,No,No
594,18,A,Admit to Ward for Care,39.1,No,No,No
595,33,A,Admit to Ward for Care,38.9,No,No,No
596,24,B,Admit to Ward for Care,37.3,No,Yes,No

In [8]:
df.columns

Index(['Age', 'Grade', 'Logistics', 'Temperature', 'Pneumonia', 'Hypertension',
       'DiabetesMellitus'],
      dtype='object')

In [9]:
len(df)

597

In [10]:
df.shape

(597, 7)

In [11]:
df.shape[0]

597

In [12]:
df.shape[1]

7

In [13]:
df.Temperature

0      37.4
1      38.0
2      38.5
3      38.2
4      38.1
       ...
592    39.9
593    39.0
594    39.1
595    38.9
596    37.3
Name: Temperature, Length: 597, dtype: float64

In [14]:
df['Temperature']

0      37.4
1      38.0
2      38.5
3      38.2
4      38.1
       ...
592    39.9
593    39.0
594    39.1
595    38.9
596    37.3
Name: Temperature, Length: 597, dtype: float64

Come faccio ad ottenere solo pazienti di grado a?

In [17]:
df[df.Grade == 'A']

,Age,Grade,Logistics,Temperature,Pneumonia,Hypertension,DiabetesMellitus
1,64,A,Admit to Ward for Care,38.0,No,Yes,No
2,87,A,Admit to Ward for Care,38.5,No,No,No
3,70,A,Admit to Ward for Care,38.2,No,No,No
7,29,A,Admit to Ward for Care,38.1,No,Yes,No
8,73,A,Admit to Ward for Care,37.9,No,No,No
...,...,...,...,...,...,...,...
589,61,A,Consultation only (leave in original ward),36.0,No,No,No
590,60,A,Consultation only (leave in original ward),37.9,No,No,No
592,54,A,Admit to Ward for Care,39.9,No,No,No
594,18,A,Admit to Ward for Care,39.1,No,No,No
595,33,A,Admit to Ward for Care,38.9,No,No,No

Se voglio temperatura maggiore di un certo valore?

In [20]:
df[df.Temperature >=39.5]

,Age,Grade,Logistics,Temperature,Pneumonia,Hypertension,DiabetesMellitus
49,22,B,Admit to Ward for Care,39.7,No,No,No
54,28,B,Admit to ICU / HCU for Care,39.5,No,No,No
60,49,B,Immediate Surgical intervention(then Ward / IC...,39.7,No,No,No
67,38,B,Immediate Surgical intervention(then Ward / IC...,39.5,No,Yes,No
72,59,A,Admit to Ward for Care,39.8,No,Yes,No
96,34,B,Admit to ICU / HCU for Care,39.9,No,No,No
103,84,A,Immediate Surgical intervention(then Ward / IC...,39.5,No,Yes,No
113,63,A,Admit to Ward for Care,39.8,No,Yes,Yes
118,26,A,Admit to ICU / HCU for Care,39.8,No,Yes,No
121,66,B,Admit to Ward for Care,39.5,No,Yes,No
126,59,A,Admit to Ward for Care,39.9,No,Yes,No
129,65,A,Consultation only (leave in original ward),39.9,No,No,No
142,63,B,Admit to Ward for Care,39.9,No,No,No
162,54,A,Immediate Surgical intervention(then Ward / IC...,39.8,No,Yes,No
167,25,B,Immediate Surgical intervention(then Ward / IC...,39.6,No,Yes,No
190,23,B,Admit to Ward for Care,39.6,No,Yes,No
191,87,B,Admit to ICU / HCU for Care,39.9,No,No,No
202,66,A,Immediate Surgical intervention(then Ward / IC...,39.5,No,Yes,Yes
204,57,A,Admit to Ward for Care,39.5,No,No,No
207,87,B,Admit to Ward for Care,39.8,No,No,No
210,40,B,Consultation only (leave in original ward),39.7,No,No,No
212,84,B,Immediate Surgical intervention(then Ward / IC...,39.5,No,No,No
218,36,B,Admit to Ward for Care,39.9,No,Yes,No
226,87,B,Admit to Ward for Care,39.6,No,No,No
234,32,A,Admit to Ward for Care,39.9,No,Yes,No
236,69,A,Admit to Ward for Care,39.9,No,Yes,No
265,24,A,Immediate Surgical intervention(then Ward / IC...,39.9,No,No,No
266,87,B,Immediate Surgical intervention(then Ward / IC...,39.8,No,No,No
289,46,B,Immediate Surgical intervention(then Ward / IC...,39.5,No,No,No
298,81,A,Admit to Ward for Care,39.9,No,No,No
304,61,A,Admit to Ward for Care,39.7,No,No,No
307,43,B,Admit to Ward for Care,39.9,No,No,No
310,21,B,Admit to Ward for Care,39.7,No,Yes,No
311,82,B,Consultation only (leave in original ward),39.9,No,No,No
314,88,B,Admit to Ward for Care,39.7,No,No,No
322,58,A,Immediate Surgical intervention(then Ward / IC...,39.9,No,No,No
328,25,A,Immediate Surgical intervention(then Ward / IC...,39.6,No,No,No
331,25,A,Admit to Ward for Care,39.5,No,Yes,No
342,85,B,Immediate Surgical intervention(then Ward / IC...,39.7,No,No,No
355,32,B,Admit to Ward for Care,39.7,No,Yes,No
356,46,A,Admit to Ward for Care,39.6,No,No,No
380,85,B,Consultation only (leave in original ward),39.7,No,Yes,No
394,57,A,Admit to ICU / HCU for Care,39.7,No,No,No
397,31,A,Admit to Ward for Care,39.5,No,Yes,No
403,69,B,Admit to Ward for Care,39.9,No,No,No
408,80,B,Consultation only (leave in original ward),39.5,No,No,No
412,45,A,Consultation only (leave in original ward),39.8,No,No,No
449,81,A,Admit to Ward for Care,39.9,No,No,No
453,40,A,Admit to Ward for Care,39.8,No,Yes,No
471,53,B,Consultation only (leave in original ward),39.9,No,No,No
501,24,A,Admit to Ward for Care,39.7,No,No,No
512,81,B,Admit to Ward for Care,39.9,No,Yes,No
513,18,A,Admit to Ward for Care,39.7,No,Yes,No
522,53,B,Admit to Ward for Care,39.9,No,No,No
573,79,B,Admit to Ward for Care,39.8,No,Yes,No
576,51,A,Consultation only (leave in original ward),39.7,No,No,No
585,40,B,Consultation only (leave in original ward),39.5,No,Yes,No
592,54,A,Admit to Ward for Care,39.9,No,No,No

Posso Combinare?

In [25]:
df[(df.Temperature >=39.5) & (df.Grade == 'A')]

,Age,Grade,Logistics,Temperature,Pneumonia,Hypertension,DiabetesMellitus
72,59,A,Admit to Ward for Care,39.8,No,Yes,No
103,84,A,Immediate Surgical intervention(then Ward / IC...,39.5,No,Yes,No
113,63,A,Admit to Ward for Care,39.8,No,Yes,Yes
118,26,A,Admit to ICU / HCU for Care,39.8,No,Yes,No
126,59,A,Admit to Ward for Care,39.9,No,Yes,No
129,65,A,Consultation only (leave in original ward),39.9,No,No,No
162,54,A,Immediate Surgical intervention(then Ward / IC...,39.8,No,Yes,No
202,66,A,Immediate Surgical intervention(then Ward / IC...,39.5,No,Yes,Yes
204,57,A,Admit to Ward for Care,39.5,No,No,No
234,32,A,Admit to Ward for Care,39.9,No,Yes,No
236,69,A,Admit to Ward for Care,39.9,No,Yes,No
265,24,A,Immediate Surgical intervention(then Ward / IC...,39.9,No,No,No
298,81,A,Admit to Ward for Care,39.9,No,No,No
304,61,A,Admit to Ward for Care,39.7,No,No,No
322,58,A,Immediate Surgical intervention(then Ward / IC...,39.9,No,No,No
328,25,A,Immediate Surgical intervention(then Ward / IC...,39.6,No,No,No
331,25,A,Admit to Ward for Care,39.5,No,Yes,No
356,46,A,Admit to Ward for Care,39.6,No,No,No
394,57,A,Admit to ICU / HCU for Care,39.7,No,No,No
397,31,A,Admit to Ward for Care,39.5,No,Yes,No
412,45,A,Consultation only (leave in original ward),39.8,No,No,No
449,81,A,Admit to Ward for Care,39.9,No,No,No
453,40,A,Admit to Ward for Care,39.8,No,Yes,No
501,24,A,Admit to Ward for Care,39.7,No,No,No
513,18,A,Admit to Ward for Care,39.7,No,Yes,No
576,51,A,Consultation only (leave in original ward),39.7,No,No,No
592,54,A,Admit to Ward for Care,39.9,No,No,No

In [30]:
df[df.Grade != 'A']

,Age,Grade,Logistics,Temperature,Pneumonia,Hypertension,DiabetesMellitus
0,77,B,Immediate Surgical intervention(then Ward / IC...,37.4,No,No,No
4,85,B,Admit to Ward for Care,38.1,No,Yes,No
5,30,B,Immediate Surgical intervention(then Ward / IC...,37.1,No,Yes,Yes
6,60,B,Admit to Ward for Care,38.0,No,Yes,No
11,74,B,Admit to Ward for Care,39.1,Yes,Yes,Yes
...,...,...,...,...,...,...,...
586,65,B,Admit to Ward for Care,35.9,No,No,No
587,37,B,Admit to Ward for Care,38.7,No,No,No
591,54,B,Consultation only (leave in original ward),38.0,No,No,No
593,40,B,Admit to Ward for Care,39.0,No,No,No
596,24,B,Admit to Ward for Care,37.3,No,Yes,No